# Pre-commit hooks.
# python3 -m pip install pre-commit
# pre-commit install

repos:

  # Format Python
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        additional_dependencies: ["toml"]
